export const ROUTES = {
  home: '/',
  howItWorks: '/how-it-works',
  lawEnforcement: '/law-enforcement',
  familyProtection: '/family-protection',
  pricing: '/pricing',
  faq: '/faq',
  security: '/security',
  privacy: '/privacy',
  terms: '/terms',
  contact: '/contact',
  login: '/login',
  signup: '/signup',

  dashboard: '/dashboard',
  dashboardIntake: '/dashboard/intake',
  dashboardConsent: '/dashboard/consent',
  dashboardBrokers: '/dashboard/brokers',
  dashboardBrokerDetail: (id: string) => `/dashboard/brokers/${id}`,
  dashboardReports: '/dashboard/reports',
  dashboardSettings: '/dashboard/settings',
  dashboardDeleteRequest: '/dashboard/delete-request',

  admin: '/admin',
  adminBrokers: '/admin/brokers',
  adminTasks: '/admin/tasks',
  adminUsers: '/admin/users',
  adminReports: '/admin/reports',
} as const
